services:
  _defaults:
    public: true

  pixel.sucuri.form.option_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Pixel\Module\Sucuri\Form\Admin\OptionType'
      - '@prestashop.core.form.identifiable_object.data_provider.customer_form_data_provider'